package ventanaPrincipal.ventanasEmpleados;

import com.google.gson.Gson;
import conexion.Conexion;
import conexion.Empleados;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel Felix
 */
public class PaneShow extends javax.swing.JPanel {

    Conexion con;
    Color init = new Color(0, 204, 255);
    Color hover = new Color(51, 102, 255);

    public PaneShow() {
        con = new Conexion();
        initComponents();
        mostrarTabla();
    }

    private void mostrarTabla() {
        DefaultTableModel model = (DefaultTableModel) tblEmpleados.getModel();
        model.setRowCount(0);
        Gson g = new Gson();
        for (String x : con.getEmpleados()) {
            Empleados em = g.fromJson(x, Empleados.class);
            model.addRow(new Object[]{em.Id, em.Nombre, em.Puesto});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        paneDetails = new javax.swing.JPanel();
        labelDetails = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Puesto"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        paneDetails.setBackground(new java.awt.Color(0, 204, 255));

        labelDetails.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        labelDetails.setForeground(new java.awt.Color(0, 0, 0));
        labelDetails.setText("    Ver Detalles");
        labelDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelDetailsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                labelDetailsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                labelDetailsMouseExited(evt);
            }
        });

        javax.swing.GroupLayout paneDetailsLayout = new javax.swing.GroupLayout(paneDetails);
        paneDetails.setLayout(paneDetailsLayout);
        paneDetailsLayout.setHorizontalGroup(
            paneDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
        );
        paneDetailsLayout.setVerticalGroup(
            paneDetailsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelDetails, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(387, 387, 387)
                .addComponent(paneDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(409, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(paneDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void labelDetailsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDetailsMouseExited
        paneDetails.setBackground(init);
    }//GEN-LAST:event_labelDetailsMouseExited

    private void labelDetailsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDetailsMouseEntered
        paneDetails.setBackground(hover);
    }//GEN-LAST:event_labelDetailsMouseEntered

    private void labelDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelDetailsMouseClicked
        try {
            int fila = tblEmpleados.getSelectedRow();
            int id = Integer.valueOf(String.valueOf(this.tblEmpleados.getValueAt(fila, 0)));
            FormDetails form = new FormDetails(id);
            form.setVisible(true);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Selecciona una fila primero");
        }
    }//GEN-LAST:event_labelDetailsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelDetails;
    private javax.swing.JPanel paneDetails;
    private javax.swing.JTable tblEmpleados;
    // End of variables declaration//GEN-END:variables
}
